config/routes.rb
Rails.application.routes.draw do


  
  devise_for :users

  get 'workers/select_items' 

  post 'workers/select_items' 

  get 'sdos/index'

  get 'sdos/edit'

  get 'sdos/destroy'

  get 'sdos/create'

  get 'sdos/update'

  get 'sdos/show'

  get 'index/edit'

  get 'index/destroy'

  get 'index/create'

  get 'index/update'

  get 'index/show'

  get 'users/index'

  get 'users/show'

  get 'users/new'

  get 'users/edit'

  get 'users/delete'

  get 'user/index'

  get 'user/show'

  get 'user/new'

  get 'user/edit'

  get 'user/delete'


  # match ':controller(/:action(:id))', :via => :get

  resources :complaints
  resources :users
  resources :workers
  resources :sdos

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/complaint.rb
class Complaint < ApplicationRecord
	belongs_to :sdo, optional: true
	belongs_to :worker, optional: true
	belongs_to :user
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :worker
end

app/models/sdo.rb
class Sdo < ApplicationRecord
  has_many :complaints
end

app/models/user.rb
class User < ApplicationRecord
  has_many :complaints

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  after_create :send_welcome_email


  def send_welcome_email
      UserNotifierMailer.sign_up(self).deliver
  end
end

app/models/worker.rb
class Worker < ApplicationRecord
 has_many :complaints
 has_many  :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  protect_from_forgery with: :exception

  before_action :authenticate_user!, except: 'complaints/index'

end

app/controllers/complaints_controller.rb
class ComplaintsController < ApplicationController

  #layout false

  def index
    http_cache_forever(public: true) {}
    if current_user.user_type == 'operator'
      @complaints = Complaint.all
    else
      @complaints = current_user.complaints
    end
  end

  def show
    http_cache_forever(public: true) {}
    @complain = Complaint.find(params[:id])
    unless current_user.user_type == 'complainer' && current_user.complaints.where(id: @complain.id).count > 0
      redirect_to :root, notice: 'You don\'t have access to this page' && return
    end
  end

  def create
    @complain = current_user.complaints.new(complain_params)
    #save the object
    if @complain.save
    # if saved redirect to index page  
    flash[:new] = "One new complain has been submitted by you!"
      redirect_to current_user
    else
    #redisplay the page to remove the errors
      render('new')
    end
  end
  
  def new
    @complain = current_user.complaints.new
  end

  def edit
    @complain = Complaint.find(params[:id])
  end

  def update
    #instaniate a new object using form paramters
    @complain = Complaint.find(params[:id])
    
    #save the object
    if @complain.update_attributes(complain_params)

      if @complain.status == 'completed'
        UserNotifierMailer.send_complain_email(@complain.user).deliver
  
      elsif @complain.status == 'accepted'
        UserNotifierMailer.sign_up(@complain.user).deliver

      elsif @complain.status == 'rejected'
        UserNotifierMailer.rejected_complain(@complain.user).deliver    
      end
    # if saved redirect to index page  
      flash[:success] = "Your complain has been updated"
      redirect_to @complain
    else
    #redisplay the page to remove the errors
      render('edit')
    end
  end

  def delete
    @complain = Complaint.find(params[:id])
  end

  def destroy
    @complain = Complaint.find(params[:id])
    @complain.destroy
    flash[:error] = "One complain has been deleted"
    redirect_to(action: 'index')
  end

  private 

  def complain_params
    params.require(:complain).permit(:title, :details, :category, :user_id, :sdo_id, :worker_id,:status)
  end
end

app/controllers/sdos_controller.rb
class SdosController < ApplicationController
  def index
    @sdos = Sdo.all
  end

  def edit
    @sdo = Sdo.find(params[:id])
  end

  def destroy
  end

  def create
  end

  def update
    #instaniate a new object using form paramters
    @sdo = Sdo.find(params[:id])
    
    #save the object
    if @sdo.update_attributes(sdo_params)
    # if saved redirect to index page  
      redirect_to(:action => 'show', :id => @sdo.id)
    else
    #redisplay the page to remove the errors
      render('edit')
    end
  end

  def show
    @sdo = Sdo.find(params[:id])
    @sdo_complaints = @sdo.complaints
  end
end

private 
  def sdo_params
    params.require(:sdo).permit(:name, :email)
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @user_complaints = @user.complaints
  end

  def new
  end

  def create
    #instaniate a new object using form paramters
    @complain = Complaint.new(complain_params)
    #save the object
    if @complain.save
    # if saved redirect to index page  
      flash[:new] = "Your complain has been updated"
      redirect_to(:action => 'index')
    else
    #redisplay the page to remove the errors
      render('new')
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    #instaniate a new object using form paramters
    @user = User.find(params[:id])
    
    #save the object
    if @user.update_attributes(user_params)
    # if saved redirect to index page  
      flash[:success] = "Your complain has been updated"
      redirect_to(:action => 'show', :id => @user.id)
    else
    #redisplay the page to remove the errors
      render('edit')
    end
  end

  def delete
  end

  private 
  def user_params
    params.require(:user).permit(:user_id, :first_name,:user_type, :last_name, :email, :phone, :address, :profession)
  end

  def complain_params
    params.require(:complain).permit(:title, :category, :user_id, :sdo_id, :worker_id)
  end

end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  

  def index
    @workers = Worker.all
  end
  def destroy
  end

  def create
  end

  def edit
    @worker = Worker.find(params[:id])
  end

  def update
    #instaniate a new object using form paramters
    @worker = Worker.find(params[:id])
    
    #save the object
    if @worker.update_attributes(worker_params)
    # if saved redirect to index page  
      redirect_to(:action => 'show', :id => @worker.id)
    else
    #redisplay the page to remove the errors
      render('edit')
    end
  end

  def select_items
    #instaniate a new object using form paramters
    @items = Item.new(params[:name])
    #save the object
    if @items.save
    # if saved redirect to index page  
      redirect_to(:action => 'show')
    else
    #redisplay the page to remove the errors
      render('select_items')
    end
  end

  def show
    @worker = Worker.find(params[:id])
    @worker_complaints = @worker.complaints
  end
end

private 
  def worker_params
    params.require(:worker).permit(:full_name, :phone)
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/complaints_helper.rb
module ComplaintsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/sdos_helper.rb
module SdosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/complaints/_form.html.erb
<%= form_for(:complain, url: { action: 'create'}) do |f| %>
	<% @complain.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>

	<table class="table table-bordered">
		<tr>
			<th>Complain Title</th>
			<td><%= f.text_field(:title) %></td>
		</tr>
		<tr>
			<th>Category</th>
			<td><%= f.text_field(:category) %></td>
		</tr>
		<tr>
			<th>Description</th>
			<td><%= f.text_area(:details) %></td>
		</tr>
	</table>
	<div class="form-button">
		<%= submit_tag('Submit Complain') %> 
	</div>
<% end %>

app/views/complaints/create.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6">
			<div><%= link_to("Go Back",{:action => 'index'}, :class => 'btn btn-default') %>				
			</div>
			<div>
				<%= form_for(:complaint, :url => {:action => 'create'}) do |complain| %>
				<table class="table">
					<tr>
						<th>Complain Title</th>
						<td><%= complain.text_field(:title) %></td>
					</tr>
					<tr>
						<th>Category</th>
						<td><%= complain.text_field(:category) %></td>
					</tr>
					<tr>
						<th>User ID/Name</th>
						<td><%= complain.text_field(:user_id) %></td>
					</tr>
					<tr>
						<th>SDO ID/Name</th>
						<td><%= complain.text_field(:sdo_id) %></td>
					</tr>
					<tr>
						<th>Worker ID/Name</th>
						<td><%= complain.text_field(:worker_id) %></td>
					</tr>
				</table>
				<% end %>
				<div class="form-button">
					<%= submit_tag('Submit Complain') %> 
				</div>
			</div>
		</div>
	</div>
</div>

app/views/complaints/delete.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 complains delete">
			<div class="btn btn-default"><%= link_to("Go Back",{:action => 'index'}, :class => 'back-to-index') %>
			</div>
			<h2>Delete Complaint</h2>
			<%= form_for(:complain, url: {:action => 'destroy', id: @complain.id}) do |complain| %>
			<p>Are you sure you want to delete this complain?</p>
			<p class="reference-title"><%= @complain.title %></p>
			<div class="form-buttons">
				<%= submit_tag('Delete Complain') %>
			</div>
			<% end %>
		</div>
	</div>
</div>

app/views/complaints/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6">
			<div class="btn btn-default"><%= link_to("Go Back",{ action: 'index'}, class: 'back-to-index') %>			
			</div>
			<div>
				<%= form_for(:complain, url: {action: 'update', id: @complain.id}, method: :put) do |complain| %>
				<table class="table table-bordered">
					<tr>
						<th>Complain Title</th>
						<td><%= complain.text_field(:title) %></td>
					</tr>
					<tr>
						<th>Category</th>
						<td><%= complain.text_field(:category) %></td>
					</tr>
					<tr>
						<th>User ID/Name</th>
						<td><%= complain.text_field(:user_id) %></td>
					</tr>
					<tr>
						<th>SDO ID/Name</th>
						<td><%= complain.text_field(:sdo_id) %></td>
					</tr>
					<tr>
						<th>Worker ID/Name</th>
						<td><%= complain.text_field(:worker_id) %></td>
					</tr>
					<tr>
						<th>Status</th>
						<td><%= complain.text_field(:status) %></td>
					</tr>
				</table>
				<div class="form-button">
					<%= submit_tag('Update Complain') %> 
				</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/complaints/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-8">
			<caption><h3>All Complaints</h3></caption>
			<table class="table table-hover table-bordered centre">
				<th>Complaint ID</th>
				<th>Title</th>
				<th>Status</th>
				<th>Actions</th>
				<% @complaints.each do |complaint| %>
				<tr>
					<td><%= complaint.id %> </td>
					<td><%= complaint.title %></td>
					<td><%= complaint.status %></td>
					<td>
						<div class="btn btn-sm btn-default">
							<%= link_to("Show details",{:action => 'show', :id => complaint.id}, :class => 'action show glyphicon glyphicon-file') %>
						</div>
						<div class="btn btn-sm btn-default">
							<%= link_to("Edit",{:action => 'edit', :id => complaint.id}, :class => 'action edit glyphicon glyphicon-edit') %>
						</div>
						<div class="btn btn-sm btn-default">
							<%=link_to "Delete",complaint_path(complaint.id), 'data-method' => :delete, class: "delete glyphicon glyphicon-remove-circle", confirm: "Are you sure ?"%>
						</div>
					</td>
				</tr>
				<% end %>
			</table> 
			<div>
				<%= link_to("Create New Complaint",{:action => 'new'}, :class => 'action create btn btn-sm btn-info') %>
			</div>
		</div>
	</div>
</div>

app/views/complaints/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6">
			<div><%= link_to("Go Back",{action: 'index'}, class: 'btn btn-default') %>				
			</div>
			<div>
				<%= form_for(:complain, url: { action: 'create'}) do |f| %>

					<% @complain.errors.full_messages.each do |msg| %>
			      <li><%= msg %></li>
			    <% end %>

					<table class="table table-bordered">
						<tr>
							<th>Complain Title</th>
							<td><%= f.text_field(:title) %></td>
						</tr>
						<tr>
							<th>Category</th>
							<td><%= f.text_field(:category) %></td>
						</tr>
						<tr>
							<th>Description</th>
							<td><%= f.text_area(:details) %></td>
						</tr>
					</table>
					<div class="form-button">
						<%= submit_tag('Submit Complain') %> 
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/complaints/show.html.erb
<div class="container">
	<div class="row">
		<caption><h3>Showing "<%= @complain.title %>" Details</h3></caption>
		<div class="col-md-11">
			<div><%= link_to("Go Back",{:action => 'index'}, :class => 'back-to-index btn btn-default') %>				
			</div>
			<table class="table tabel-hover table-bordered">
				<th>Complaint ID</th>
				<th>Title</th>
				<th>Category</th>
				<th>User ID</th>
				<th>SDO ID</th>
				<th>Worker ID</th>
				<th>Status</th>
				<th>Registered Date</th>
				<th>Updated Date</th>
				<tr>
					<td><%= @complain.id %> </td>
					<td><%= @complain.title %></td>
					<td><%= @complain.category %></td>
					<td><%= @complain.user.first_name %></td>
					<td><%= @complain.sdo.name %></td>
					<td><%= @complain.worker.full_name %></td>
					<td><%= @complain.status %></td>
					<td><%= @complain.created_at%></td>
					<td><%= @complain.updated_at %></td>
				</tr>
			</table> 
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ComplaintManagementSystem</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

  	<div class="container">
	  <div class="row">
	    <div class="col-md-7">
            <%= image_tag ('logo.png'), size: "50x50", alt: "Logo"%> 
	      <span style="color: #25D872;font-size: 24px;margin-left: 5px;">UET Complaint Management and Maintenance System</span>
	    </div>
	    <div class="col-md-5 n
        avbar" role='navigation'>
        <ul class="nav nav-tabs ">
          <li class="<%= 'active' if controller_name == 'complaints' %>">
            <%= link_to "Complains", '/complaints', class: 'glyphicon glyphicon-list-alt' %>
          </li>
          <li class="<%= 'active' if controller_name == 'users' %>">
            <%= link_to "Users", '/users/index', class: ' glyphicon glyphicon-user' %>
          </li>
          <li class="<%= 'active' if controller_name == 'sdos' %>">
            <%= link_to "SDOs", '/sdos/index', class: ' glyphicon glyphicon-user' %>
          </li>
          <li class="<%= 'active' if controller_name == 'workers'%>">
            <%= link_to "Workers", '/workers', class: ' glyphicon glyphicon-user' %>
          </li>
          <li>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
          </li>
        </ul>
	    </div>
	  </div>
    <hr>
	</div>
  <% if flash[:success] %>
    <div class="notice alert alert-success"><%= flash[:success] %></div>
  <% end %>
  <% if flash[:error] %>
    <div class="notice alert alert-danger"><%= flash[:error] %></div>
  <% end %>
  <% if flash[:new] %>
    <div class="notice alert alert-warning"><%= flash[:new] %></div>
  <% end %>


    <%= yield %>
  </body>
</html>

app/views/sdos/create.html.erb
<h1>Sdos#create</h1>
<p>Find me in app/views/sdos/create.html.erb</p>

app/views/sdos/destroy.html.erb
<h1>Sdos#destroy</h1>
<p>Find me in app/views/sdos/destroy.html.erb</p>

app/views/sdos/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6">
			<div><%= link_to("Go back",{:action => 'edit'}, :class => 'back-to-index btn btn-default') %>			
			</div>
			<div>
				<%= form_for(:sdo, url: {action: 'update', id: @sdo.id}, method: :put) do |sdo| %>
				<table class="table table-bordered">
					<tr>
						<th>Full Name</th>
						<td><%= sdo.text_field(:name) %></td>
					</tr>
					<tr>
						<th>Email</th>
						<td><%= sdo.text_field(:email) %></td>
					</tr>
				</table>
				<div class="form-button">
					<%= submit_tag('Update Credentials') %> 
				</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/sdos/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-10">
			<div>

				<% @sdos.each do |sdo| %>
					<table class="table table-bordered">
						<tr>
							<th>SDO ID</th>
							<th>Full Name</th>
							<th>Email</th>
							<th>CNIC No</th>
						</tr>
						 <tr>
						 	<td>
						 		<div><%= link_to("#{sdo.id}",{:action => 'show', id: sdo.id}, :class => 'individual btn btn-warning') %>			
						 		</div>
						 	</td>
							<td>
								<%= sdo.name %>
							</td>
							<td>
								<%= sdo.email %>
							</td>
							<td>
								<%=  sdo.cnic %>
							</td>
							<br>
					</table>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/sdos/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-8">
		<%= form_for(:sdos, url: {action: 'index', id: @sdo.id}, method: :put) do |sdo| %>	
			<caption><h3>Complaints Supervised by  
				<!-- Split button -->
				<div class='btn-group'>
				  <button type='button' class='btn btn-success'><%= "#{@sdo.name}" %></button>
				  <button type='button' class='btn btn-default dropdown-toggle' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
				    <span class='caret'></span>
				    <span class='sr-only'>Toggle Dropdown</span>
				  </button>
				  <ul class='dropdown-menu'>
				    <li><%= link_to "Edit details", {:action => 'edit'}, :id => "sdo_details" %>	</li>
				  </ul>
				</div>
			</h3></caption>
			<hr>
			<table class="table table-hover table-bordered centre">
				<th>SDO ID</th>
				<th>SDO Name</th>
				<th>Complaint ID</th>
				<th>Title</th>
				<th>Complainer</th>
				<th>Worker Name</th>
				<th>Status</th>
				<% @sdo_complaints.each do |complaint| %>
				<tr>
					<td><%= @sdo.id %></td>
					<td><%= @sdo.name %></td>
					<td><%= complaint.id %> </td>
					<td><%= complaint.title %></td>
					<td><%= complaint.user.first_name %></td>
					<td><%= complaint.worker.full_name %></td>
					<td><%= complaint.status %></td>
				</tr>
				<% end %>
			</table> 
		<% end %>
		</div>
	</div>
</div>

app/views/sdos/update.html.erb
<h1>Sdos#update</h1>
<p>Find me in app/views/sdos/update.html.erb</p>

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6">
			<div><%= link_to("Go back",{ action: 'index' }, class: 'back-to-index btn btn-default') %>			
			</div>
			<div>
				<%= form_for(:user, url: {action: 'update', id: @user.id}, method: :put) do |user| %>
				<table class="table table-bordered">
					<tr>
						<th>First Name</th>
						<td><%= user.text_field(:first_name) %></td>
					</tr>
					<tr>
						<th>Last Name</th>
						<td><%= user.text_field(:last_name) %></td>
					</tr>
					<tr>
						<th>User Type</th>
						<td><%= user.text_field(:user_type) %></td>
					</tr>
					<tr>
						<th>Email</th>
						<td><%= user.text_field(:email) %></td>
					</tr>
					<tr>
						<th>Phone</th>
						<td><%= user.text_field(:phone) %></td>
					</tr>
					<tr>
						<th>Address</th>
						<td><%= user.text_field(:address) %></td>
					</tr>
					<tr>
						<th>Profession</th>
						<td><%= user.text_field(:profession) %></td>
					</tr>
				</table>
				<div class="form-button">
					<%= submit_tag('Update Credentials') %> 
				</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-10">
			<div>

				<% @users.each do |user| %>
					<table class="table table-bordered">
						<tr>
							<th>User ID</th>
							<th>First Name</th>
							<th>Last Name</th>
							<th>User Type</th>
							<th>Email</th>
							<th>Phone</th>
							<th>Address</th>
							<th>Profession</th>
						</tr>
						 <tr>
						 	<td>
						 		<%= link_to("#{user.id}",{ action: 'show', id: user.id}, class: 'individual btn btn-warning') %>
						 	</td>
							<td>
								<%= user.first_name %>
							</td>
							<td>
								<%=  user.last_name %>
							</td>
							<td>
								<%=  user.user_type %>
							</td>
							<td>
								<%= user.email %>
							</td>
							<td>
								<%= user.phone %>
							</td>
							<td>
								<%= user.address %>
							</td>
							<td>
								<%= user.profession %>
							</td>
							</tr>
							<br>
					</table>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/users/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6">
			<div><%= link_to("Go Back",{:action => 'index'}, :class => 'back-to-index btn btn-default') %>				
			</div>
			<div>
				<%= render 'complaints/form' %>
			</div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
		<%= form_for(:users, url: {action: 'index', id: @user.id}, method: :put) do |user| %>	
			<caption><h3>Complaints by 
				<!-- Split button -->
				<div class='btn-group'>
				  <button type='button' class='btn btn-success'><%= "#{@user.first_name} #{@user.last_name}" %></button>
				  <button type='button' class='btn btn-default dropdown-toggle' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
				    <span class='caret'></span>
				    <span class='sr-only'>Toggle Dropdown</span>
				  </button>
				  <ul class='dropdown-menu'>
				    <li><%= link_to "Edit details", {:action => 'edit'}, :id => "user_details" %>	</li>
				  </ul>
				</div>
			</h3></caption>
			<hr>
			<table class="table table-hover table-bordered centre">
				<th>Complaint ID</th>
				<th>Title</th>
				<th>Complainer</th>
				<th>Status</th>
				<th>Supervising SDO</th>
				<th>Assigned Worker</th>
				<th>Updated at</th>
				<% @user_complaints.each do |complaint| %>
				<tr>
					<td><%= complaint.id %> </td>
					<td><%= complaint.title %></td>
					<td><%= @user.first_name%> <%= @user.last_name %> </td>
					<td><%= complaint.status %></td>
					</td>
					<% if complaint.sdo.present? %>
						<td> <%= complaint.sdo.name %> </td>
					 <% end %>
					 <% if complaint.worker.present? %>
					<td><%= complaint.worker.full_name %></td>
					<% end %>
					<td><%= complaint.updated_at %></td>
				</tr>
				<% end %>
			</table> 
			<div>
				<%= link_to("Create New Complaint",new_complaint_path, class: 'action create btn btn-sm btn-default' ) %>
			</div>
		<% end %>
		</div>
	</div>
</div>

app/views/workers/create.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-5">
			<div>
				<%= form_for(:complain, :url => {:action => 'create'}) do |complain| %>
					<table class="table table-bordered">
						<tr>
							<th>Complain Title</th>
							<td><%= complain.text_field(:title) %></td>
						</tr>
						<tr>
							<th>Category</th>
							<td><%= complain.text_field(:category) %></td>
						</tr>
						<tr>
							<th>User ID/Name</th>
							<td><%= complain.text_field(:user_id) %></td>
						</tr>
						<tr>
							<th>SDO ID/Name</th>
							<td><%= complain.text_field(:sdo_id) %></td>
						</tr>
						<tr>
							<th>Worker ID/Name</th>
							<td><%= complain.text_field(:worker_id) %></td>
						</tr>
					</table>
					<div class="form-button">
						<%= submit_tag('Submit Complain') %> 
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/workers/destroy.html.erb
<h1>Index#destroy</h1>
<p>Find me in app/views/index/destroy.html.erb</p>

app/views/workers/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6">
			<div><%= link_to("Go back",{:action => 'edit'}, :class => 'back-to-index btn btn-default') %>			
			</div>
			<div>
				<%= form_for(:worker, url: {action: 'update', id: @worker.id}, method: :put) do |worker| %>
				<table class="table table-bordered">
					<tr>
						<th>Full Name</th>
						<td><%= worker.text_field(:full_name) %></td>
					</tr>
					<tr>
						<th>Phone</th>
						<td><%= worker.text_field(:phone) %></td>
					</tr>
				</table>
				<div class="form-button">
					<%= submit_tag('Update Credentials') %> 
				</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/workers/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-10">
			<div>

				<% @workers.each do |worker| %>
					<table class="table table-bordered">
						<tr>
							<th>worker ID</th>
							<th>Full Name</th>
							<th>CNIC No</th>
							<th>Phone</th>
						</tr>
						 <tr>
						 	<td>
						 		<div><%= link_to("#{worker.id}",{:action => 'show', id: worker.id}, :class => 'individual btn btn-warning') %>			
						 		</div>
						 	</td>
							<td>
								<%= worker.full_name %>
							</td>
							<td>
								<%=  worker.cnic %>
							</td>
							<td>
								<%= worker.phone %>
							</td>
							<br>
					</table>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/workers/select_items.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-5">
			<div>
				<%= form_for(:@items, :url => {:action => 'select_items'}) do |item| %>
					<table class="table table-bordered">
						<tr>
							<th>Item Name</th>
							<th>Cost</th>
							
						</tr>
						<tr>
							<td><%= item.text_field(:name) %></td>
							<td><%= item.text_field(:cost) %></td>
						</tr>
						<tr>
							<td><%= item.text_field(:name) %></td>
							<td><%= item.text_field(:cost) %></td>
						</tr>
						<tr>
							<td><%= item.text_field(:name) %></td>
							<td><%= item.text_field(:cost) %></td>
						</tr>
						<tr>
							<th>Total cost</th>
							<td><%= item.text_field(:total_cost) %></td>
						</tr>
					</table>
					<div class="form-button">
						<%= submit_tag('Save') %> 
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/workers/update.html.erb
<h1>Index#update</h1>
<p>Find me in app/views/index/update.html.erb</p>